### PR TITLE
Fix userpopup not showing room rank

### LINKED ISSUE #1300: Room group is incorrectly displayed in UserPopup
Regression from 8e9bc3fe1e739a92c8b25075a6a0479ffc56e0aa

> [15:39:50] Flare ✇: Um is someone else having the issue of not being able to see room ranks...? http://prntscr.com/o13vol http://prntscr.com/o13vqo http://prntscr.com/o13vsq http://prntscr.com/o13vys

It is almost like this was something I warned about...

> It is very challenging to trace through not just the immediate callers of `parseNameParts` but the things they pass 'name' to etc

_Originally posted by @scheibo in https://github.com/Zarel/Pokemon-Showdown-Client/pull/1287_

Relevant section of code is here:

https://github.com/Zarel/Pokemon-Showdown-Client/blob/8d4dc632b927b41c8ea31aced5fd7b4b1c590549/js/client.js#L2462-L2472

I don't really know whats going on here - we include the room group in the `name` and global group as a separate `group` field? I dont know where this is being called from - do we instead want to make data have `globalgroup` and `group` fields instead of shoehorning `group` into name?

### PR DESCRIPTION
**Pull request by TheJetOU**
Closes #1300
It's called `roomGroup`  because `group` would shadow the server's response in `/cmd userdetails`.

### CODE REVIEW

File: js/client-chat.js [hunk 1]
```diff
@@ -1723,7 +1724,7 @@
 			// Sanitising the `userid` here is probably unnecessary, because
 			// IDs can't contain anything dangerous.
 			text += '<li' + (this.room.userForm === userid ? ' class="cur"' : '') + ' id="' + this.room.id + '-userlist-user-' + BattleLog.escapeHTML(userid) + '">';
-			text += '<button class="userbutton username" data-name="' + BattleLog.escapeHTML(user.name) + '"';
+			text += '<button class="userbutton username" data-roomgroup="' + user.group + '"data-name="' + BattleLog.escapeHTML(user.name) + '"';
```
Comment (scheibo) [inline js/client-chat.js]:
```suggestion
			text += '<button class="userbutton username" data-roomgroup="' + user.group + '" data-name="' + BattleLog.escapeHTML(user.name) + '"';
```

File: js/client-chat.js [hunk 2]
```diff
@@ -1723,7 +1724,7 @@
 			// Sanitising the `userid` here is probably unnecessary, because
 			// IDs can't contain anything dangerous.
 			text += '<li' + (this.room.userForm === userid ? ' class="cur"' : '') + ' id="' + this.room.id + '-userlist-user-' + BattleLog.escapeHTML(userid) + '">';
-			text += '<button class="userbutton username" data-name="' + BattleLog.escapeHTML(user.name) + '"';
+			text += '<button class="userbutton username" data-roomgroup="' + user.group + '" data-name="' + BattleLog.escapeHTML(user.name) + '"';
```
Comment (Zarel) [inline js/client-chat.js]: `escapeHTML`...............
